# from: https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html and https://github.com/google/brotli-wheels/blob/master/.travis.yml
language: generic
python: 3.7

matrix:
 exclude:
  - python: 3.6
 include:
  - os: linux
    sudo: required
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=2.7
  - os: linux
    sudo: required
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=3.5
  - os: linux
    sudo: required
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=3.6
  - os: linux
    sudo: required
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=3.7
  - os: osx
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=2.7
  - os: osx
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=3.5
  - os: osx
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=3.6
  - os: osx
    compiler: gcc
    env:
     - CONDA_PYTHON_VERSION=3.7

install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
   else
    sudo apt-get update;
   fi
 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
   else
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
   fi
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a

 - conda create -q -n build-environment python=$CONDA_PYTHON_VERSION
 - conda create -q -n test-environment python=$CONDA_PYTHON_VERSION
 - source activate build-environment
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - source activate test-environment
 - pip install pytest pytest-cov codecov

before_script:
 - source activate build-environment
 - python setup.py build_ext --inplace
 - python setup.py bdist_wheel
 - source activate test-environment
 - pip install --find-links=dist neuroglia

script:
 - source activate test-environment
 - pytest --cov=neuroglia
 - codecov

deploy:
 - provider: releases
   tag: $TRAVIS_TAG
   api_key: $GITHUB_TOKEN
   file_glob: true
   file: "dist/*"
   skip_cleanup: true
   draft: false
   prerelease: true
   on:
    tags: true
